micronaut:
  server:
    cors:
      enabled: true
#      configurations:
#        web:
#          allowedOrigins:
#          - http://localhost:8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:MammaLikerKaffe378lkdlk=90234?}"'

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/curiousbear
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
jpa:
  default:
    packages-to-scan:
      - 'com.kodebjorn'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3